### ISSUE TITLE
E_WARNING: Missing argument 14 for ParserPowerLists::applyTemplateToList(), called in extensions/ParserPower/includes/ParserPowerLists.php on line 1992 and defined

### ISSUE THREAD

**Issue by Alexia** [oOeyes/ParserPower#1]
Thrown on: http://strife.gamepedia.com/Frost_Prism

…t extensions/ParserPower/includes/in ParserPowerLists::applyTemplateToList called at extensions/ParserPower/includes/ParserPowerLists.php
ParserPowerLists.php (1795)
…t extensions/ParserPower/includes/ParserPowerLists.php (1992)
in ParserPowerLists::lstmaptempRender called at ? (?)
…l_user_func_array called at includes/parser/Parser.php (3789)
…allParserFunction called at includes/parser/Parser.php (3523)
…itution called at includes/parser/Preprocessor_DOM.php (1177)
…Frame_DOM::expand called at includes/parser/Parser.php (3780)
…allParserFunction called at includes/parser/Parser.php (3523)
…itution called at includes/parser/Preprocessor_DOM.php (1177)
…at extensions/ParserFunctions/ParserFunctions_body.php (104)
in ExtParserFunctions::ifObj called at ? (?)
…l_user_func_array called at includes/parser/Parser.php (3789)
…allParserFunction called at includes/parser/Parser.php (3523)
…itution called at includes/parser/Preprocessor_DOM.php (1177)
…Frame_DOM::expand called at includes/parser/Parser.php (3665)
…itution called at includes/parser/Preprocessor_DOM.php (1177)
…Frame_DOM::expand called at includes/parser/Parser.php (3342)
…:replaceVariables called at includes/parser/Parser.php (1239)
…er::internalParse called at includes/parser/Parser.php (439)
…::parse called at includes/content/WikitextContent.php (331)

**Comment by oOeyes** [comment]
Fixed in 1.0.1, now available.

**Comment by Alexia** [comment]
Thanks!  I will deploy this soon to live.
